language: go

go:
  - "1.20.x"

env:
  global:
    - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest
  - golangci-lint --version

install:
  - go test -race -cover -coverprofile=coverage.txt -covermode=atomic ./...
  - go mod download

script:
  golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)