AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AlexaSkill with ChatGPT

Globals:
  Function:
    Timeout: 300
    Environment:
      Variables:
        RESPONSES_QUEUE_URI: !Ref ResponsesQueue
        REQUESTS_QUEUE_URI: !Ref RequestsQueue
        OPENAI_API_KEY: !Ref ApiKey
        POLL_DELAY: 7

Parameters:
  ApiKey:
    Type: String
    Description: OpenAI API Key

  Runtime:
    Type: String
    Default: go1.x

  Architecture:
    Type: String
    Default: "x86_64"

  Handler:
    Type: String
    Default: main

Resources:

  RequestsQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub ${AWS::StackName}-Requests
      RedrivePolicy:
        maxReceiveCount: 5
        deadLetterTargetArn: !GetAtt RequestsDLQ.Arn
      VisibilityTimeout: 301

  RequestsDLQ:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub ${AWS::StackName}-Requests-DLQ

  ResponsesQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub ${AWS::StackName}-Responses
      VisibilityTimeout: 301

  ChatGPTFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: !Ref Runtime
      Handler: !Ref Handler
      Architectures:
        - !Ref Architecture
      FunctionName: chatGPT
      CodeUri: .
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref ApiKey
      Policies:
        - SQSPollerPolicy:
            QueueName:
              !GetAtt ResponsesQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt RequestsQueue.QueueName
    Metadata:
      BuildMethod: makefile

  ChatGPTRequests:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: !Ref Runtime
      Handler: !Ref Handler
      Architectures:
        - !Ref Architecture
      FunctionName: chatGPTRequests
      CodeUri: .
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RequestsQueue.Arn
            BatchSize: 1
      Policies:
        - SQSSendMessagePolicy:
            QueueName:
              !GetAtt ResponsesQueue.QueueName
    Metadata:
      BuildMethod: makefile

Outputs:
  ChatGPTLambdaArn:
    Description: "chatGPT alexa skill lambda ARN"
    Value: !GetAtt ChatGPTFunction.Arn

  ChatGPTRequestsArn:
    Description: "chatGPT requests handling lambda ARN"
    Value: !GetAtt ChatGPTRequests.Arn

  RequestsQueue:
    Description: "chatGPT prompt requests queue"
    Value: !GetAtt RequestsQueue.Arn

  RequestsDLQ:
    Description: "chatGPT prompt requests dead letter queue"
    Value: !GetAtt RequestsDLQ.Arn

  ResponsesQueue:
    Description: "chatGPT responses queue"
    Value: !GetAtt ResponsesQueue.Arn
